-- Step 1.5 (NOMOCK): remove data that earlier code fabricated. Irreversible by design.

-- 1. Product sources that are not real marketplace products:
--    the fake "mock" platform, placeholder/anti-bot/error-page titles, and search-result pages.
CREATE TEMP TABLE fake_sources ON COMMIT DROP AS
SELECT id FROM product_sources
WHERE platform = 'mock'
   OR canonical_url ILIKE '%mock.dealhunter.vn%'
   OR raw_title IS NULL
   OR btrim(raw_title) = ''
   OR raw_title IN ('San pham', 'San pham Shopee', 'San pham Lazada', 'San pham TikTok Shop', 'Security Check')
   OR raw_title ILIKE 'Xin lỗi!%'
   OR canonical_url ILIKE '%/catalog/?q=%';

-- Tables without ON DELETE CASCADE first
DELETE FROM tracked_products WHERE product_source_id IN (SELECT id FROM fake_sources);
DELETE FROM price_snapshots  WHERE product_source_id IN (SELECT id FROM fake_sources);
DELETE FROM fetch_jobs       WHERE product_source_id IN (SELECT id FROM fake_sources);
-- alert_rules (+ notification_logs), product_vouchers and comparison_snapshots cascade
DELETE FROM product_sources  WHERE id IN (SELECT id FROM fake_sources);

-- 2. Products left without any source (match suggestions and comparison snapshots cascade)
DELETE FROM products p WHERE NOT EXISTS (SELECT 1 FROM product_sources s WHERE s.product_id = p.id);

-- 3. Seller names that adapters invented when the page did not state one
UPDATE product_sources SET seller_name = NULL
WHERE seller_name IN ('Shopee Shop', 'Shopee Seller', 'Shopee Official', 'LazMall Official', 'TikTok Shop Official');

-- 4. Vouchers generated by the removed voucher seeder (they all pointed at generic hub pages)
DELETE FROM product_vouchers
WHERE collect_url IN (
    'https://shopee.vn/m/ma-giam-gia',
    'https://shopee.vn/m/mien-phi-van-chuyen',
    'https://www.lazada.vn/voucher',
    'https://www.tiktok.com/tag/voucher'
);
