-- Step 1.5 (NOMOCK): remove data that earlier code fabricated. Irreversible by design.

-- 1. Product sources that are not real marketplace products:
--    the fake "mock" platform, placeholder/anti-bot/error-page titles, and search-result pages.
--    Sources created by POST /track never stored raw_title (the title lived only in products.title),
--    so the title is taken from raw_title when present and from the product otherwise.
CREATE TEMP TABLE fake_sources ON COMMIT DROP AS
SELECT s.id
FROM product_sources s
JOIN products p ON p.id = s.product_id
CROSS JOIN LATERAL (SELECT btrim(COALESCE(NULLIF(btrim(s.raw_title), ''), p.title, '')) AS title) t
WHERE s.platform = 'mock'
   OR s.canonical_url ILIKE '%mock.dealhunter.vn%'
   OR t.title = ''
   OR t.title IN ('San pham', 'San pham Shopee', 'San pham Lazada', 'San pham TikTok Shop', 'Security Check')
   OR t.title ILIKE 'Xin lỗi!%'
   OR s.canonical_url ILIKE '%/catalog/?q=%';

-- Tables without ON DELETE CASCADE first
DELETE FROM tracked_products WHERE product_source_id IN (SELECT id FROM fake_sources);
DELETE FROM price_snapshots  WHERE product_source_id IN (SELECT id FROM fake_sources);
DELETE FROM fetch_jobs       WHERE product_source_id IN (SELECT id FROM fake_sources);
-- alert_rules (+ notification_logs), product_vouchers and comparison_snapshots cascade
DELETE FROM product_sources  WHERE id IN (SELECT id FROM fake_sources);

-- 2. Products left without any source (match suggestions and comparison snapshots cascade)
DELETE FROM products p WHERE NOT EXISTS (SELECT 1 FROM product_sources s WHERE s.product_id = p.id);

-- 3. Seller names that adapters invented when the page did not state one
UPDATE product_sources SET seller_name = NULL
WHERE seller_name IN ('Shopee Shop', 'Shopee Seller', 'Shopee Official', 'LazMall Official', 'TikTok Shop Official');

-- 4. Vouchers generated by the removed voucher seeder (they all pointed at generic hub pages)
DELETE FROM product_vouchers
WHERE collect_url IN (
    'https://shopee.vn/m/ma-giam-gia',
    'https://shopee.vn/m/mien-phi-van-chuyen',
    'https://www.lazada.vn/voucher',
    'https://www.tiktok.com/tag/voucher'
);
